J1: 1.0
J2: 0.0
Lx: 6
Ly: null
M: 1
ansatz: qgps
b1: null
b2: null
chains: 1
sweeps: null
constrained: false
diagonal-shift: 0.01
discard: 100
dtype: real
iterations: 100
learning-rate: 0.01
optimizer: sgd-sr
sampler: metropolis-exchange
samples: 100
sigma: 0.1
sign-rule: true
sr-iterative: true
symmetries: all